### ISSUE TITLE
Bug: Signature Approvals overriding Max Allowance already 

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#4428]
**Bug Description**
Users with a max Allowance on USDC and DAI are being forced to do a signature approval, instead of the UI noticing that they already have full allowance set. Swap button shows up momentarily then goes to signature approval 

**Steps to Reproduce**

1. Go to app.uniswap.org
2. With a wallet supplied with USDC with max allowance
3. Add USDC to sell
4. Instead of Swap, get signature approval
   ...

**Expected Behavior**
The UI should notice non signature allowance, and not force the signature

**Additional Context**
![image](https://user-images.githubusercontent.com/60412342/185771794-9272d225-4cdd-483a-b8b4-f73c65240a0a.png)
![image](https://user-images.githubusercontent.com/60412342/185771796-ef4583df-7991-4e00-b448-4a8400bdfb62.png)

**Comment by Rachel-Eichenberger** [comment]
looks like this has been resolved
@alien2108 can you confirm

**Comment by alien2108** [comment]
Just tested it out. Issue persist. I still get Signature request first and after canceling approval request.
